language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t nlaparo/react-test -f ./client/Dockerfile.dev ./client

#script:
# - docker run -e CI=true nlaparo/react-test npm test

after_success:
 - docker build -t nlaparo/multi-client ./client
 - docker build -t nlaparo/multi-server ./server
 - docker build -t nlaparo/multi-nginx ./nginx
 - docker build -t nlaparo/multi-worker ./worker
 # log into the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take those images and push them to docker hub
 - docker push nlaparo/multi-client
 - docker push nlaparo/multi-server
 - docker push nlaparo/multi-nginx
 - docker push nlaparo/multi-worker



